dev_addr: 127.0.0.1:8001

docs_dir: src/acme/service/oculus/docs

extra_css:
  - static/css/extra.css

plugins:
- mkdocstrings:
    enable_inventory: false
    handlers:
      python:
        rendering:
          show_bases: no
          show_object_full_path: yes
          show_signature_annotations: yes
          show_source: no
        setup_commands:
          - import os
          - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "acme.service.oculus.conf")
          - import django
          - django.setup()
    watch:
      - src/acme/service/oculus

site_name: Oculus

theme:
  features:
    - navigation.expand
    - navigation.top
  language: en
  name: material
  palette:
    primary: green
