# Generated by Django 4.0.1 on 2022-01-16 04:36

import acme.service.oculus.models.application
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('apikey', models.CharField(default=acme.service.oculus.models.application.get_encrypted_apikey, max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
